	@ List all Soundtrack ID's here.
	@ There are also Jingles in the Modules, for that see jingles.inc.
	.set SOUNDTRACK_STRANGETOWN,           0x0
	.set SOUNDTRACK_STRANGETOWN_EDIT,      0x1
	.set SOUNDTRACK_STRANGETOWN_EDIT2,     0x2
	.set SOUNDTRACK_CREDITS,               0x3
	.set SOUNDTRACK_BOARDROOM,             0x4
	.set SOUNDTRACK_STRANGE_DAY,           0x5
	.set SOUNDTRACK_STRANGE_NIGHT,         0x6
	.set SOUNDTRACK_DUSTYHOGG_BLUES,       0x7
	.set SOUNDTRACK_EDGE_OF_TOWN,          0x8
	.set SOUNDTRACK_INTIMIDATE,            0x9
	.set SOUNDTRACK_ALIENS,                0xA
	.set SOUNDTRACK_CALMNESS,              0xB
	.set SOUNDTRACK_THE_GOONS,             0xC
	.set SOUNDTRACK_TRANCE_MODE,           0xD
	.set SOUNDTRACK_HEAVY_METAL,           0xE
	.set SOUNDTRACK_SPEED_METAL,           0xF
	.set SOUNDTRACK_ROMANCE,               0x10
	.set SOUNDTRACK_FRIENDSHIP,            0x11
	.set SOUNDTRACK_SWEETNESS,             0x12
	.set SOUNDTRACK_BLOOM,                 0x13
	.set SOUNDTRACK_INVESTIGATE,           0x14
	.set SOUNDTRACK_BIGFOOT_LOVE_CHICKENS, 0x1D
	.set SOUNDTRACK_KEELHAULIN_CARDS,      0x1F
	.set SOUNDTRACK_CHUG_CHUG_COLA,        0x20
